#!/usr/bin/env python3
"""Generate deterministic Markdown reference pages from suite metadata."""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path
from typing import Dict, List


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from salsbury_md_analysis.cli import build_parser  # noqa: E402
from salsbury_md_analysis.registry import MODULES, ModuleSpec  # noqa: E402


def _escape(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def render_module_reference() -> str:
    lines = [
        "# Module reference",
        "",
        "> Generated by `scripts/generate_docs.py`; edit the registry, not this file.",
        "",
        "| ID | Stage | Category | Status | Title |",
        "|---|---:|---|---|---|",
    ]
    for module in MODULES:
        lines.append(
            f"| `{_escape(module.module_id)}` | {_escape(module.stage or '-')} | "
            f"{_escape(module.category)} | **{_escape(module.status)}** | {_escape(module.title)} |"
        )

    for module in MODULES:
        lines.extend(
            [
                "",
                f"## {module.title}",
                "",
                f"- ID: `{module.module_id}`",
                f"- Stage: `{module.stage or '-'}`",
                f"- Category: `{module.category}`",
                f"- Status: **{module.status}**",
                "",
                module.summary,
                "",
                "Required inputs:",
                "",
            ]
        )
        lines.extend(f"- {item}" for item in module.required_inputs)
        lines.extend(["", "Declared outputs:", ""])
        lines.extend(f"- {item}" for item in module.outputs)
        lines.extend(["", "Scientific limits:", ""])
        lines.extend(f"- {item}" for item in module.scientific_limits)
    return "\n".join(lines) + "\n"


def render_analysis_coverage() -> str:
    statuses = Counter(module.status for module in MODULES)
    lines = [
        "# Analysis coverage",
        "",
        "> Generated from the MD module registry and standard-analysis profile.",
        "",
        "## Suite module status",
        "",
        "| Status | Count |",
        "|---|---:|",
    ]
    for status in ("supported", "experimental", "planned", "deprecated"):
        lines.append(f"| {status} | {statuses.get(status, 0)} |")
    lines.extend(
        [
            "",
            f"Registered suite modules: **{len(MODULES)}**.",
            "",
            "Registration alone is not an implementation claim. Experimental modules have code and tests, but are not production-supported.",
            "",
            "## Standard profile",
            "",
            "The versioned `standard_md_v1` profile is the comprehensive, nonredundant public analysis path. New generally reusable methods should enter the registry and profile only after their contract, tests, documentation, and scientific limits are defined.",
        ]
    )
    lines.extend(
        [
            "",
            "## Release gate",
            "",
            "`v1.0` requires every standard-profile module to have reviewed scientific contracts, "
            "independent regression evidence, maintained documentation, and an explicitly supported status. "
            "Passing unit tests or one trajectory validation is necessary but not sufficient.",
        ]
    )
    return "\n".join(lines) + "\n"


def render_profiles() -> str:
    lines = [
        "# Profile reference",
        "",
        "> Generated from `profiles/**/*.json`.",
    ]
    by_id = {module.module_id: module for module in MODULES}
    for path in sorted((ROOT / "profiles").glob("*.json")):
        profile = json.loads(path.read_text(encoding="utf-8"))
        if "profile_id" not in profile or "modules" not in profile:
            continue
        lines.extend(
            [
                "",
                f"## {profile['profile_id']}",
                "",
                f"- Version: `{profile['profile_version']}`",
                f"- Status: **{profile['status']}**",
                "",
                profile["description"],
                "",
                "| Order | Module | Current status |",
                "|---:|---|---|",
            ]
        )
        for index, module_id in enumerate(profile["modules"], start=1):
            status = by_id[module_id].status
            lines.append(f"| {index} | `{module_id}` | {status} |")
    lines.extend(["", "## Execution configs"])
    for path in sorted((ROOT / "profiles" / "analysis").glob("*.json")):
        config = json.loads(path.read_text(encoding="utf-8"))
        if config.get("config_schema") != "salsbury-analysis-config-v1":
            raise ValueError(f"unrecognized analysis config: {path}")
        execution = config.get("execution", {})
        lines.extend([
            "",
            f"### {path.stem}",
            "",
            f"Source: `{path.relative_to(ROOT)}`",
            "",
            f"- Adapter: `{execution.get('submission_adapter', 'local')}`",
            f"- Parallel CPU limit: `{execution.get('maximum_parallel_cpus', 'default')}`",
            f"- Campaign wall-hour limit: `{execution.get('maximum_hours_per_cpu', 'default')}`",
            f"- Slurm profile: `{execution.get('slurm_profile') or 'none'}`",
        ])
    lines.extend(["", "## Slurm cluster profiles"])
    for path in sorted((ROOT / "profiles" / "slurm").glob("*.json")):
        profile = json.loads(path.read_text(encoding="utf-8"))
        if profile.get("slurm_profile_schema") != "salsbury-slurm-profile-v1":
            raise ValueError(f"unrecognized Slurm profile: {path}")
        partitions = profile.get("partitions", {})
        partition_node_limits = profile.get("partition_maximum_nodes", {})
        environment = profile.get("environment", {})
        resource_policy = profile.get("resource_policy", {})
        lines.extend([
            "",
            f"### {profile['profile_id']}",
            "",
            f"Source: `{path.relative_to(ROOT)}`",
            "",
            f"- Cluster: `{profile['cluster_name']}`",
            f"- Account: `{profile.get('account') or 'site/user default'}`",
            f"- Unix group: `{profile.get('unix_group') or 'site/user default'}`",
            f"- QoS: `{profile.get('qos') or 'site/user default'}`",
            f"- Default partition: `{partitions.get('default') or 'site/user default'}`",
            f"- Analysis partition: `{partitions.get('analysis') or 'default'}`",
            f"- Conformational partition: `{partitions.get('conformational') or 'default'}`",
            f"- Large-memory partition: `{partitions.get('large_memory') or 'default'}`",
            "- Partition node limits: `"
            + (
                json.dumps(partition_node_limits, sort_keys=True)
                if partition_node_limits else "site defaults"
            )
            + "`",
            f"- Large-memory threshold GiB: `{resource_policy.get('large_memory_threshold_gib', 'default')}`",
            f"- Python executable: `{environment.get('python_executable') or 'site/user default'}`",
        ])
    catalog_paths = sorted(
        (ROOT / "profiles").glob("apollo_measured_resource_calibrations_v*.json")
    )
    if catalog_paths:
        catalog_path = catalog_paths[-1]
        catalog = json.loads(catalog_path.read_text(encoding="utf-8"))
        lines.extend([
            "",
            "## Measured resource calibration",
            "",
            f"Source: `{catalog_path.relative_to(ROOT)}`",
            "",
            f"Measured entries: **{len(catalog.get('entries', []))}**.",
            f"Completed executions: **{catalog.get('complete_execution_count', 'not recorded')}**.",
            f"Right-censored timeouts: **{catalog.get('censored_timeout_count', 'not recorded')}**.",
        ])
    return "\n".join(lines) + "\n"


def render_schemas() -> str:
    lines = ["# Schema reference", "", "> Generated from `schemas/*.json`."]
    for path in sorted((ROOT / "schemas").glob("*.json")):
        schema = json.loads(path.read_text(encoding="utf-8"))
        required = set(schema.get("required", []))
        lines.extend(
            [
                "",
                f"## {schema.get('title', path.stem)}",
                "",
                f"Source: `{path.relative_to(ROOT)}`",
                "",
                "| Field | Required | Type or constraint |",
                "|---|---|---|",
            ]
        )
        for name, definition in schema.get("properties", {}).items():
            constraint = definition.get("type") or definition.get("enum") or definition.get("$ref") or "structured"
            lines.append(
                f"| `{_escape(name)}` | {'yes' if name in required else 'no'} | `{_escape(constraint)}` |"
            )
    return "\n".join(lines) + "\n"


def render_cli() -> str:
    parser = build_parser()
    return "\n".join(
        [
            "# Command-line reference",
            "",
            "> Generated from the actual argument parser.",
            "",
            "```text",
            parser.format_help().rstrip(),
            "```",
            "",
            "Inspection and experimental analysis commands are read-only and emit reports to standard output. Experimental does not mean production-supported.",
            "",
        ]
    )


def generated_pages() -> Dict[Path, str]:
    generated = ROOT / "docs" / "generated"
    return {
        generated / "MODULE_REFERENCE.md": render_module_reference(),
        generated / "ANALYSIS_COVERAGE.md": render_analysis_coverage(),
        generated / "PROFILE_REFERENCE.md": render_profiles(),
        generated / "SCHEMA_REFERENCE.md": render_schemas(),
        generated / "CLI_REFERENCE.md": render_cli(),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if generated pages are stale.")
    args = parser.parse_args()
    stale: List[str] = []
    for path, expected in generated_pages().items():
        actual = path.read_text(encoding="utf-8") if path.exists() else None
        if actual == expected:
            continue
        if args.check:
            stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
    if stale:
        print("Stale or missing generated documentation:")
        for item in stale:
            print(f"- {item}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
