"""Authoritative registry of intended and implemented analysis modules.

The registry is deliberately explicit. A module is not implemented merely because it
appears here; status must remain ``planned`` until reviewed code and tests exist.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

from .ensemble_parallelism import validate_registry_coverage
from .reporting import DataclassRecordMixin


VALID_STATUSES = {"planned", "experimental", "supported", "deprecated"}
VALID_CATEGORIES = {"core", "md", "reporting"}


@dataclass(frozen=True)
class ModuleSpec(DataclassRecordMixin):
    module_id: str
    title: str
    category: str
    stage: Optional[str]
    status: str
    summary: str
    required_inputs: Tuple[str, ...]
    outputs: Tuple[str, ...]
    scientific_limits: Tuple[str, ...]
    first_supported_version: Optional[str] = None

    def __post_init__(self) -> None:
        if self.status not in VALID_STATUSES:
            raise ValueError(f"Invalid module status {self.status!r}")
        if self.category not in VALID_CATEGORIES:
            raise ValueError(f"Invalid module category {self.category!r}")
        if not self.module_id or any(char.isspace() for char in self.module_id):
            raise ValueError("module_id must be nonempty and contain no whitespace")
        if self.status == "supported" and not self.first_supported_version:
            raise ValueError("supported modules require first_supported_version")

def _module(
    module_id: str,
    title: str,
    category: str,
    stage: Optional[str],
    summary: str,
    required_inputs: Tuple[str, ...],
    outputs: Tuple[str, ...],
    scientific_limits: Tuple[str, ...],
    status: str = "planned",
) -> ModuleSpec:
    return ModuleSpec(
        module_id=module_id,
        title=title,
        category=category,
        stage=stage,
        status=status,
        summary=summary,
        required_inputs=required_inputs,
        outputs=outputs,
        scientific_limits=scientific_limits,
    )


MODULES: Tuple[ModuleSpec, ...] = (
    _module("provenance_manifest", "Provenance and immutable manifests", "core", "1", "Validate project, system, output, and publication-lock manifests; compile explicit units, selections, and system/replica/segment identities; and produce deterministic input inventories with optional SHA-256 hashes.", ("project configuration", "system manifest", "declared units", "named selections"), ("validated manifests", "compiled analysis context", "context signature", "input inventory", "input hashes"), ("Provenance records technical lineage; it does not establish trajectory readability, convergence, population meaning, or scientific validity.",), status="experimental"),
    _module("preflight_inventory", "Trajectory and topology preflight", "md", "1", "Inspect supported topology and trajectory metadata, compare atom counts, and check declared DCD segment continuity without loading coordinates.", ("validated system manifest", "topologies", "trajectories"), ("format-aware preflight report", "technical issues", "input metadata"), ("Current DCD support reads declared header metadata rather than coordinate records or actual frame counts.", "Passing preflight does not demonstrate chemical correctness, equilibration, convergence, adequate sampling, or scientific validity."), status="experimental"),
    _module("common_atom_mapping", "Validated common-atom mapping", "core", "1", "Create deterministic PDB/GRO atom maps across variants using explicit strict or position identity, atom selection, coverage gates, exclusions, and a stable mapping signature.", ("reference topology", "one or more target topologies", "mapping policy", "selection", "coverage threshold"), ("common atom map", "mapping signature", "coverage", "mapping exclusions", "mutation warnings"), ("Identity mapping does not perform sequence or structural alignment.", "The position policy ignores residue-name substitutions and requires prevalidated numbering correspondence.", "Weakly homologous systems must not be forced onto a whole-protein common basis."), status="experimental"),
    _module("structural_integrity_qc", "Structural integrity and unusual-state QC", "md", "2", "Stream supported coordinates and apply explicit readability, atom-count, finite-coordinate, extent, displacement, peptide-continuity, omega, C-alpha chirality, element-radius clash, and declared covalent-link gates.", ("validated project context", "trajectory segments", "topology", "explicit QC thresholds", "optional declared covalent links"), ("replica/segment QC report", "technical issues", "chemical-integrity examples", "quarantine evidence"), ("Chemical checks require explicit settings and connectivity-aware periodic reconstruction for production trajectories.", "The conservative steric screen excludes same-residue pairs and does not replace specialized cofactor, metal, or force-field validation.", "Thresholds must be declared before comparative outcome review."), status="experimental"),
    _module("replica_rmsd_rg", "Replica-resolved RMSD and radius of gyration", "md", "3", "Stream replica/segment trajectories, fit a declared common selection to an explicit reference, and calculate unweighted RMSD plus mass-weighted radius of gyration with mapping and coverage evidence.", ("validated project context", "PDB/GRO topology", "supported trajectories", "reference structure", "named selections", "mapping policy", "coverage threshold"), ("replica/segment timeseries", "metric summaries", "mapping signatures", "coverage and limitation report"), ("RMSD is primarily stability and QC evidence, not functional importance.", "Periodic molecules must be made whole before this experimental implementation can support wrapped production trajectories.", "Frame indices do not become physical time without an explicit trajectory timing contract.", "Technical completion does not establish equilibration, convergence, adequate sampling, or scientific validity."), status="experimental"),
    _module("pooled_rmsf", "Replica-pooled RMSF with uncertainty", "md", "4", "Fit a globally common atom basis and stream frame-pooled RMSF while retaining separate per-replica and explicit frame-block estimates with sample SD/SEM only when estimable.", ("validated project context", "PDB/GRO topologies", "supported trajectories", "reference structure", "named alignment and analysis selections", "mapping and coverage policy", "frame-block specification"), ("frame-pooled RMSF profile", "per-replica RMSF profiles", "time-block profiles", "between-replica and block summaries", "RMSF-in-B-factor PDB and VMD NewCartoon export", "mapping and lineage evidence"), ("Frames are not independent uncertainty units.", "Frame-pooled and replica-balanced RMSF are distinct estimators and must remain labeled.", "Time-block estimates are convergence diagnostics, not automatically independent replicates.", "RMSF stored in a PDB B-factor field remains RMSF in angstrom and is not a crystallographic B factor.", "Periodic molecules must be made whole before wrapped production trajectories can be interpreted.", "Technical completion does not establish equilibration, convergence, adequate sampling, or scientific validity."), status="experimental"),
    _module("dccm", "Dynamic cross-correlation", "md", "5", "Stream fitted coordinates into replica and frame-pooled Cartesian displacement cross-correlation matrices on one global atom basis, with explicit zero-variance and quadratic-size gates plus reference-system differences.", ("validated project context", "PDB/GRO topologies", "supported trajectories", "reference structure and system", "named selections", "mapping and coverage policy", "variance, size, frame, and stride gates"), ("per-replica DCCMs", "system-pooled DCCMs", "reference-system difference matrices", "undefined-entry and off-diagonal summaries", "mapping and lineage evidence"), ("Generalized correlation and mutual information require separately labeled methods.", "Null zero-variance entries must not be interpreted as zero correlation.", "Frame-pooled matrices are not replica-level uncertainty estimates.", "Correlation does not establish causality, directionality, mechanism, or significance.", "Periodic molecules must be made whole before wrapped production trajectories can be interpreted."), status="experimental"),
    _module("generalized_correlation_and_information", "Generalized correlation and mutual information", "md", "5N", "Estimate symmetric nonlinear dependence between declared common-PCA features using explicit quantile histograms, natural-log mutual information, normalized mutual information, and the scalar generalized-correlation transform.", ("common PCA projections", "selected feature indices", "bin-count and observation gates"), ("marginal entropies", "mutual-information matrices", "normalized mutual-information matrices", "generalized-correlation matrices", "feature lineage"), ("Histogram information estimates require bin-count and sample-size sensitivity analysis.", "The current provider uses scalar common-PCA features; residue-vector and distance-feature providers remain extensions.", "Symmetric dependence does not establish direction, causality, or mechanism."), status="experimental"),
    _module("individual_pca", "Individual-replica PCA", "md", "6", "Fit each replica to an explicit reference and calculate a separate population-covariance PCA basis, deterministic component orientation, variance accounting, and physical-time or sample-index projections with feature, frame, periodicity, and solver gates.", ("validated project context", "PDB/GRO topologies", "supported trajectories", "reference structure", "named selections", "mapping and coverage policy", "feature, frame, component, and stride gates"), ("per-replica means", "eigenvalues and explained variance", "component loadings", "physical-time or sample-index projections", "solver and mapping evidence"), ("Coordinates from independently fitted PCA bases are not directly comparable.", "Frames are not independent uncertainty units.", "Near-degenerate subspaces require sensitivity analysis.", "Periodic molecules must be made whole before wrapped production trajectories can be interpreted."), status="experimental"),
    _module("common_pca", "Common-atom shared-basis PCA", "md", "6", "Fit one global common-atom PCA basis across all declared replicas using an explicit frame-weighted or equal-replica population mixture and an exact dense or gated leading-component solver selected from feature dimensions, then project the declared trajectory frames onto that shared basis and report reference-system differences.", ("validated project context", "PDB/GRO topologies", "supported trajectories", "reference structure and system", "named selections", "mapping and coverage policy", "basis weighting", "feature-aware solver and sample-matrix limits", "independent basis-fit and projection frame contracts"), ("global mean and common atom basis", "eigenvalues and explained variance", "component loadings", "shared projections", "replica/system projection summaries", "reference-system mean differences", "solver residual and resource evidence"), ("Unequal sampling and atom-map choices require separate sensitivity runs.", "Basis subsampling is computational and does not prove scientific convergence.", "Frames are not independent uncertainty units.", "Near-degenerate subspaces require subspace-level comparison.", "Periodic molecules must be made whole before wrapped production trajectories can be interpreted."), status="experimental"),
    _module("time_lagged_independent_component_analysis", "Time-lagged independent component analysis", "md", "6K", "Fit reversible, segment-safe TICA components to declared common-PCA features using symmetrized endpoint and lagged covariances, covariance-rank gates, and explicit physical lag time.", ("unbiased-MD common PCA projections", "selected PCA components", "lag and covariance settings", "segment identities and physical timing"), ("instantaneous and lagged covariances", "TICA eigenvalues and loadings", "segment-resolved projections", "implied timescale diagnostics", "numerical residuals"), ("Lag pairs never cross segment boundaries.", "Current kinetic interpretation requires unbiased MD and one common evaluated physical-time interval.", "TICA modes and timescales require lag, feature, stationarity, and convergence sensitivity analysis."), status="experimental"),
    _module("random_feature_koopman", "Random-feature nonlinear Koopman kinetics", "md", "6R", "Map selected TICA coordinates through isotropic-Gaussian random Fourier dictionaries, fit segment-safe reversible slow modes, scan feature-count and bandwidth candidates, and withhold selection unless held-out VAMP-E and slow-subspace recovery are stable across several prespecified feature-map seeds.", ("complete unbiased-MD TICA projections", "selected TICA components", "lag and random-feature hyperparameter grids", "at least three prespecified feature-map seeds", "VAMP-E and subspace-stability gates"), ("candidate-specific held-out VAMP-E", "seed-pair slow-subspace similarities", "selected nonlinear slow coordinates only after stability gates pass", "random-feature dictionary and projection lineage", "nonlinear implied-timescale diagnostics"), ("Random Fourier features approximate a declared Gaussian kernel and do not prove that kernel is physically appropriate.", "Seeds alter the fitted nonlinear representation, so a recorded multi-seed stability gate is mandatory.", "Hyperparameter selection reuses the declared validation folds and remains sensitivity evidence rather than independent confirmation.", "Nonlinear coordinates and implied timescales do not establish metastability, convergence, Markovianity, mechanism, or causality."), status="experimental"),
    _module("pca_fes_basins", "PCA free-energy surfaces and basin populations", "md", "7", "Construct declared two-dimensional histogram grids using explicit counts or independently applied Scott, Freedman-Diaconis, or Rice rules; preserve raw counts while scanning declared Gaussian smoothing widths; calculate deterministic steepest-occupancy watershed basins, minima, frame assignments, smoothing agreement, basin silhouette diagnostics, and replica/segment-block population tables; convert density to relative free energy only for unweighted unbiased MD with declared temperature.", ("common PCA projections", "temperature for unbiased MD", "sampling/weight model", "explicit bins or automatic binning rule and gates", "declared smoothing widths", "grid and basin thresholds"), ("relative FES or nonthermodynamic occupancy grids", "raw counts and bin-selection evidence", "smoothing-resolved minima and basins", "frame assignments", "exact or seeded estimated basin silhouette diagnostics", "replica and block population tables", "cross-smoothing agreement"), ("Raw AI-ensemble counts are labeled occupancy and are never converted to thermodynamic free energy.", "Biased or enhanced sampling fails closed until a validated reweighting model is implemented.", "Basin silhouette is secondary PCA-plane separation evidence and never defines minima or selects smoothing.", "Histogram, smoothing, and basin definitions require sensitivity analysis and do not establish metastability or kinetics."), status="experimental"),
    _module("clustering_kmeans", "KMeans clustering", "md", "8", "Select complete tICA, common-PCA, or trajectory-feature partitions using a declared k grid and dependency-free deterministic strat_all/strat_reduced NANI initialization by default; retain seeded KMeans++ as a compatibility sensitivity, with convergence, occupancy, multi-seed silhouette-selection, and adjusted-Rand initialization-stability evidence.", ("tICA, common PCA, or declared trajectory features", "component or feature selection", "cluster grid", "NANI strategy and candidate percentage or legacy random seeds", "occupancy, size, multi-seed silhouette, and unanimous-selection gates"), ("complete assignments", "centers", "initial-center and complementary-MSD provenance", "per-initialization diagnostics", "exact-or-multi-seed-estimated silhouette provenance", "silhouette winner-stability gate", "initialization-stability evidence"), ("A high silhouette score and initialization stability do not establish physical metastability, convergence, or kinetics.", "NANI changes KMeans initialization, not its Euclidean convex-cluster assumption.", "The NANI percentage and strat_all versus dense-state-focused strat_reduced choice require sensitivity analysis."), status="experimental"),
    _module("clustering_hdbscan", "HDBSCAN sensitivity clustering", "md", "8", "Use the optional reference hdbscan package to scan density parameters while reporting noise, retained coverage, retained-only silhouette, and complete assignment identities.", ("common PCA features", "component selection", "minimum-cluster-size and minimum-samples grids", "hdbscan optional dependency"), ("noise-aware assignments", "retained coverage", "cluster-size and parameter diagnostics", "reference-package provenance"), ("Noise-excluding clusters are a sensitivity analysis and are not complete kinetic assignments.", "Silhouette must be read together with retained coverage.", "The optional hdbscan dependency must be installed separately."), status="experimental"),
    _module("clustering_imwkmeans", "Intelligent Minkowski weighted KMeans", "md", "8", "Provide a deterministic iMWK-Means implementation with Lp centers, cluster-specific feature weights, and k/p/initialization sensitivity scans.", ("common PCA features", "component selection", "k and p grids", "initialization ranks", "occupancy and size gates"), ("complete assignments", "Lp centers", "cluster feature weights", "grid and initialization diagnostics"), ("Ordinary KMeans must not be relabeled as iMWK-Means.", "Feature weights are descriptors of the fitted partition, not mechanistic importance scores.", "Partitions do not establish metastability, convergence, or kinetics."), status="experimental"),
    _module("representative_frames", "Representative frames for clusters and PCA basins", "md", "8R", "Select one or more observed frames nearest each declared KMeans center or PCA-basin root with deterministic identity tie-breaking and no coordinate-file mutation.", ("complete KMeans assignments or PCA-FES basin assignments", "state centers", "representative-count and resource gates"), ("state-resolved representative frame locators", "center distances", "selection and upstream lineage"), ("Representatives are observed frames, not arithmetic average structures.", "Selection inherits every feature, scaling, clustering, and basin-definition choice from its source module.", "A representative frame does not establish metastability, convergence, mechanism, or scientific validity."), status="experimental"),
    _module("state_coordinate_exports", "Immutable state trajectories and structures", "md", "8E", "Materialize state-resolved multi-frame PDB or XYZ trajectories and observed representative PDB structures from declared FES or clustering assignments, using periodic reconstruction and an atomic fail-if-present output directory.", ("complete FES or clustering assignments", "declared output ID and format", "frame and state resource gates", "validated topology and trajectory identities"), ("state/system/replica trajectory files", "observed representative PDB structures", "checksummed export manifest", "source-frame lineage"), ("Source trajectories are never edited or overwritten.", "Unlike system or replica topologies are never silently combined.", "Exported subsets and representatives do not establish metastability, convergence, kinetics, mechanism, or scientific validity."), status="experimental"),
    _module("markov_state_models", "Markov-state models", "md", "9", "Build segment-safe transition models for every enabled complete clustering partition, select the best clustering model by kinetic validation, retain a separately reported FES-basin model, and report explicitly enabled noise-censored HDBSCAN only as a conditional sensitivity; Ward and quality-threshold are omitted unless they provide exact complete assignments over every observation; scan lag times, estimators, implied-timescale stability, Chapman-Kolmogorov consistency, time-blocked VAMP validation, and block-bootstrap uncertainty.", ("complete enabled clustering assignments", "optional noise-censored HDBSCAN sensitivity assignments", "primary PCA-FES basin assignments", "physical frame timing", "segment identities", "lag, VAMP, CK, and bootstrap settings"), ("best geometric clustering", "best kinetically validated complete clustering model", "separate FES state model", "separate HDBSCAN core MSM sensitivity", "count and transition matrices", "stationary distributions and reversible implied timescales", "connectivity, CK, VAMP-E, implied-timescale stability, and block-bootstrap diagnostics"), ("Transitions are never joined across segment, noise-gap, or bootstrap-block boundaries.", "Noise-censored HDBSCAN is a conditional sensitivity and never enters primary MSM selection.", "Ward and quality-threshold are skipped unless their exact fit assigns every observation.", "The clustering and FES state definitions are both reported and are not treated as interchangeable.", "Rates and pathways are not valid until sampling, lag, connectivity, population, and convergence gates pass.", "Technical completion does not establish a valid kinetic model."), status="experimental"),
    _module("reactive_path_ensembles", "Reactive-path ensembles from ordinary MD", "md", "9P", "Reuse complete KMeans frame assignments and their trajectory features; discover a recurrent endpoint pair or accept disjoint multi-state source and sink sets; extract segment-safe last-exit/first-arrival paths; compare bounded path ensembles with multidimensional dynamic time warping; cluster route families; and report explicit transition-sufficiency and kinetics-readiness gates.", ("complete KMeans assignments with frame identity, physical time, and feature values", "automatic recurrent-pair or explicit disjoint multi-state endpoints", "DTW, route-clustering, resource, and event-sufficiency gates", "optional validated KMeans Markov-state report"), ("endpoint-selection inventory", "complete source-to-sink and sink-to-source path records", "endpoint transition-count matrix", "pairwise normalized DTW distances", "route clusters and medoid representative paths", "transition-sufficiency and kinetics-readiness status"), ("Paths never cross system, replica, segment, or member boundaries.", "Automatically selected KMeans endpoints have no inferred biological meaning and are not assumed metastable.", "DTW route families are descriptive and do not establish mechanism, flux, committor probability, or causality.", "Ordinary MD cannot characterize a transition it did not observe; absent or insufficient transitions are reported explicitly.", "A kinetics-ready status is a prerequisite gate and not a rate estimate."), status="experimental"),
    _module("dihedral_distributions", "Backbone and side-chain dihedral distributions", "md", "10", "Stream declared phi, psi, omega, and conventional protein chi1-chi5 torsions with reference-distance peptide-link gates and residue-resolved circular summaries.", ("accepted trajectories", "PDB/GRO topology", "declared torsion types", "reference peptide-link threshold"), ("residue and replica circular statistics", "angular histograms", "definition and periodicity diagnostics"), ("Local mutation effects and distal effects must be distinguished.", "Nonstandard residues require an explicit future torsion adapter rather than guessed atom names.", "Circular distributions do not establish convergence or significance."), status="experimental"),
    _module("hydrogen_bonds", "Hydrogen-bond occupancies", "md", "11", "Evaluate explicitly indexed donor-hydrogen-acceptor features using declared distance and angle rules, with optional KMeans-state conditioning and fail-closed water/periodicity policies.", ("accepted trajectories", "topology with explicit hydrogens", "indexed hydrogen-bond features", "distance, angle, water, and conditioning rules"), ("feature occupancies", "mean geometry", "optional cluster-conditioned occupancies", "definition and periodicity diagnostics"), ("Definitions and inclusion rules must accompany every occupancy result.", "The current implementation excludes water-mediated bonds.", "Occupancy does not establish energetic or mechanistic importance."), status="experimental"),
    _module("hydrogen_bond_discovery", "Topology-template hydrogen-bond discovery", "md", "11D", "Automatically enumerate a frozen direct donor-hydrogen-acceptor dictionary from standard protein/nucleic-acid chemistry templates and explicit connectivity, with auditable provisional fallback for untemplated ligands; retain an explicit atom-index mode for publication locks, outcome-independent atom-identity harmonization for homologous systems, labeled interaction strata, exact periodic spatial screening, and optional fixed-width packed sparse output for large candidate universes.", ("accepted trajectories", "explicit connectivity", "automatic interaction scope or publication-locked explicit features", "primary and sensitivity geometry rules"), ("candidate bond dictionary with interaction strata", "dense, sparse-list, or packed sparse frame-by-bond observations", "observed geometry", "directly readable primary occupancies", "exact packed sensitivity occupancies", "chemistry, harmonization, and geometry-engine provenance"), ("Automatic chemistry cannot repair missing or incorrect protonation, tautomer, formal charge, or ligand bond order.", "Common-candidate harmonization excludes system-specific chemical candidates from a comparative matrix before coordinates are evaluated; retain separate per-system discovery for those features.", "Spatial screening retains the complete candidate dictionary and assigns exact implicit zeros to candidates outside the largest distance cutoff; it does not apply outcome-dependent feature selection.", "Packed sparse frames use single-precision geometry and preserve exact cutoff membership; they do not imply greater physical precision than the source coordinates.", "Packed sensitivity occupancies are exact nonzero count tables; absent candidate-cutoff records are evaluated zeros under the report's explicit-zero contract.", "This direct-bond module excludes water-mediated paths, which have a separate contract.", "Occupancy does not establish energetic or mechanistic importance."), status="experimental"),
    _module("hydrogen_bond_comparison", "Grouped chemical-identity hydrogen-bond comparison", "md", "11C", "Compare exactly two technically complete sparse direct-hydrogen-bond discovery reports after collapsing connectivity-equivalent donor hydrogens into one donor-heavy-atom/acceptor-heavy-atom event per frame; align nonidentical topologies only through explicit project-supplied chemical-homolog mappings.", ("two sparse hydrogen-bond discovery reports", "identical interaction scope and cutoff definition", "condition labels", "optional explicit chemical-homolog mappings"), ("equal-replica and pooled grouped occupancies", "condition occupancy differences", "per-replica evidence", "mapping and source-report provenance"), ("Homolog mappings are chemical assertions and are never inferred by the implementation.", "Equal-replica descriptive means do not establish independent sampling or convergence.", "Occupancy differences do not establish energy, affinity, causality, or mechanism."), status="experimental"),
    _module("water_mediated_hydrogen_bond_networks", "Water-mediated hydrogen-bond networks", "md", "11W", "Discover one-water solute bridges from automatic solute chemistry and connectivity-backed water identity, evaluate edges with a spatial cell list and exact periodic geometry, and report cutoff sensitivity, exchange-aware residence, direct coincidence, networks, and observed representatives.", ("accepted solvated trajectories", "explicit solute and water connectivity", "standard water residue identity", "interaction scope", "primary and sensitivity geometry rules", "resource gates"), ("sparse frame water paths", "observed bridge dictionary", "cutoff-resolved bridge occupancies", "any-water and same-water residence runs", "network summaries", "representative frame locators"), ("The first implementation supports exactly one bridging water, not multi-water wires or proton hopping.", "The observed bridge union is not an outcome-independent machine-learning feature universe.", "Water-network geometry and occupancy do not establish energy, affinity, causality, or mechanism."), status="experimental"),
    _module("grouped_ml", "Grouped-validation machine learning", "md", "11", "Run deterministic decision-tree classification with complete segment-time-block holdouts, confusion matrices, and held-out permutation diagnostics; estimator extensions remain explicit.", ("KMeans PCA feature table", "explicit KMeans technical target", "segment/time-block group labels", "tree and permutation settings"), ("fold and pooled held-out metrics", "confusion matrices", "final tree", "impurity and held-out permutation diagnostics"), ("Chance-level performance and impurity importance alone do not support mechanism.", "The current target is a technical clustering target derived from the input features and is not a biological endpoint.", "Random-forest support remains a separately validated extension."), status="experimental"),
    _module("grouped_regularized_classification", "Grouped logistic and elastic-net classification", "md", "11M", "Classify declared systems from hydrogen-bond patterns using nested leave-one-group-out selection of L2 logistic and elastic-net models, outer held-out metrics, coefficients, and training-only top-feature ablations.", ("hydrogen-bond discovery matrix", "system targets", "replica, segment, or time-block groups", "regularization grids"), ("nested tuning diagnostics", "outer held-out metrics", "coefficients", "top-feature and no-top-feature ablations"), ("Replica grouping is preferred; time blocks cannot manufacture independent replicas.", "Predictive coefficients and performance are not causal or mechanistic evidence.", "Every class requires at least two independent groups."), status="experimental"),
    _module("secondary_structure", "Secondary structure", "md", "12", "Execute an explicitly selected mkdssp binary on local temporary per-frame PDBs and retain executable/version, frame, residue, and periodicity provenance.", ("accepted trajectories", "PDB topology", "mkdssp executable", "frame and resource gates"), ("frame assignment counts", "residue-level DSSP code populations", "executable provenance", "periodicity diagnostics"), ("Pooled estimates must retain replica-sensitive uncertainty.", "The external mkdssp executable is required and no heuristic method is mislabeled as DSSP.", "The executable's code alphabet is preserved: DSSP 4.6 PPII code P must be mapped explicitly before comparison with older code alphabets.", "Periodic production analysis requires explicit connectivity-aware reconstruction."), status="experimental"),
    _module("nucleic_acid_structure", "Nucleic-acid structural motifs", "md", "12N", "Execute an explicitly selected x3dna-dssr binary in JSON mode on temporary per-frame PDBs and retain executable/version, requested collection fields, explicit wildcard numeric descriptors, frame identities, and replica-resolved summaries.", ("accepted trajectories", "PDB/GRO topology", "x3dna-dssr executable", "declared JSON collection fields and optional numeric-query paths", "frame, timeout, and resource gates"), ("frame-level motif collection counts", "numeric base-pair/base-step/groove/helical/backbone/sugar descriptors requested by path", "replica summaries", "observed JSON keys", "executable and command provenance"), ("DSSR is an external dependency; JSON paths and missing-value policies must be declared explicitly and may vary by DSSR version.", "Periodic production analysis requires connectivity-aware reconstruction.", "Motif counts and structural descriptors require replica-sensitive convergence analysis."), status="experimental"),
    _module("helical_mechanics", "DSSR-gated duplex helical mechanics", "md", "12M", "For DSSR-verified duplex DNA or RNA only, assemble frame-aligned shift, slide, rise, tilt, roll, and twist vectors, separate supported multimodal states, estimate regularized state-specific covariance stiffness matrices, and quantify neighboring-step state coupling.", ("installed and version-recorded x3dna-dssr", "DSSR-detected duplex stem", "six frame-aligned base-step descriptor queries", "temperature", "state and covariance gates"), ("explicit available/not-available status", "step-resolved state populations", "regularized covariance and stiffness matrices", "adjacent-step joint states and mutual information"), ("The module is unavailable without DSSR or a DSSR-detected duplex stem.", "Stiffness is a local harmonic covariance model and is never fitted across an unresolved multimodal mixture.", "Translation-rotation matrices use mixed angstrom/radian coordinates.", "DSSR step ordering, state count, regularization, sampling, and replica sensitivity require validation.", "Mechanical association does not establish causality or biological mechanism."), status="experimental"),
    _module("nucleic_acid_geometry", "Intrinsic nucleic-acid ring and stacking geometry", "md", "12G", "Calculate explicit-ring fitted-plane displacement, cyclic torsion departure from 0/180 degrees, signed centering, declared fused-ring fold and base-stacking plane angles, centroid distances, early/late drift, blocks, and independent Scott/FD/Rice distributions.", ("accepted trajectories", "PDB/GRO topology", "cyclic ordered ring atom indices", "declared fused-ring or stacking pairs", "stride, block, histogram, and resource gates"), ("frame-level intrinsic ring metrics", "fused-fold and stacking geometry", "replica and block summaries", "early/late shifts", "histograms, assignments, and segment-safe residence runs"), ("Intrinsic ring puckering, whole-base reorientation, fused-ring fold, and stacking are distinct metrics.", "Ring identities and pass thresholds belong in project or publication locks.", "Periodic production analysis requires connectivity-aware reconstruction."), status="experimental"),
    _module("ion_coordination_geometry", "Bound-ion coordination and ion-pair geometry", "md", "12I", "Analyze arbitrary declared bound ions, candidate coordinating atoms, ion-pair distances, coordination numbers, ligand identities and occupancies, nearest distances, and rotation-free pair-angle deviations from declared ideal coordination templates.", ("accepted trajectories", "PDB/GRO topology", "explicit ion and candidate-ligand atom indices", "coordination cutoffs", "optional ion pairs and geometry templates", "histogram and resource gates"), ("frame-level coordination records", "bound-ligand identities and occupancies", "ion-pair distances", "geometry-template scores", "replica/block summaries and independent scalar distributions"), ("Coordination cutoffs and ideal templates are project-specific and must be sensitivity-tested.", "Geometric agreement does not determine electronic structure, protonation, affinity, or catalytic importance.", "Pass thresholds and biological interpretation belong in project or publication locks."), status="experimental"),
    _module("ion_atmosphere", "Species-resolved ion atmosphere", "md", "12A", "Measure exact triclinic minimum-image shells for every supported ion species present around all-solute, protein, nucleic-acid, and ligand/cofactor polar target groups, retaining system, replica, segment, frame, species, charge-class, and ion identity.", ("accepted periodic trajectories", "PDB/GRO topology", "species-resolved ion atom indices", "polar target atom groups", "shell cutoffs and frame gates"), ("species-target shell timeseries", "species-resolved shell summaries", "per-ion inner-shell occupancy and descriptive persistence", "frame and periodicity provenance"), ("Atmosphere shells and persistence classes are geometric and do not establish biological binding, affinity, oxidation state, or mechanism.", "Shell cutoffs require chemistry-specific sensitivity analysis.", "Cross-replica, oligomer-member, and cross-system inference requires an explicit independent-unit model."), status="experimental"),
    _module("solvent_accessible_surface_area", "Solvent-accessible surface area", "md", "12", "Calculate deterministic atom-, residue-, and selection-level Shrake-Rupley SASA using explicit surface and occluder selections, Bondi-style radii, probe radius, sphere-point resolution, and periodic reconstruction policy.", ("accepted trajectories", "PDB/GRO topology", "named surface and occluder selections", "probe and resolution settings"), ("atom and residue SASA", "selection total timeseries", "replica summaries", "periodicity and algorithm provenance"), ("Project execution refuses fewer than 240 sphere points and warns below the 960-point cross-validation setting; publication comparisons still require resolution sensitivity.", "Wrapped periodic execution is refused; connectivity-aware reconstruction is required.", "Disconnected-component image conventions require independent validation.", "Surface-area changes do not establish binding, stability, or mechanism."), status="experimental"),
    _module("radial_distribution_functions", "Radial distribution functions", "md", "12R", "Calculate replica-resolved radial distribution functions for explicit atom groups using triclinic minimum-image distances, exact spherical-shell volumes, per-frame cell-volume normalization, and safe half-cell radius gates.", ("accepted trajectories with periodic cells", "PDB/GRO topology", "explicit atom-index groups", "radial range, bin width, stride, and resource gates"), ("raw and uniform-expected shell counts", "g(r) by replica", "cell-volume and pair-count provenance", "segment evaluation counts"), ("The radial range may not exceed half the minimum triclinic face height.", "Replica RDFs remain separate until an independent-unit pooling model is declared.", "RDF peaks do not by themselves establish specific interactions, binding, or mechanism."), status="experimental"),
    _module("optional_observables", "Question-driven optional observables", "md", "12", "Evaluate extensible question-linked observables; the current base slice implements explicit pair and group-distance families, contacts, and reference-defined native-contact fractions, while domain-specific ring, ion, and RDF analyses retain separate contracts.", ("accepted trajectories", "observable question", "explicit atom-index specification", "distance/contact/native-reference threshold where applicable"), ("observable timeseries", "distance summaries", "contact and native-contact occupancies", "periodicity and provenance diagnostics"), ("Modules must answer a declared scientific or structural question.", "Water networks, membrane deformation, and experimental forward models require separately validated extensions.", "Raw wrapped-coordinate distances are diagnostic only."), status="experimental"),
    _module("convergence_uncertainty", "Convergence, uncertainty, and population validity", "md", "13", "Evaluate declared RMSD/Rg block stability, split-mean agreement, overlap-normalized autocorrelation sequences, initial-positive-sequence effective sample size, autocorrelation-adjusted mean uncertainty, and population-validity gates; optional replica summaries are exploratory only.", ("replica RMSD/Rg or other scalar timeseries", "replica and segment labels", "block, autocorrelation, ESS, and split-mean gates", "optional replica-diagnostics choice"), ("per-series convergence and autocorrelation diagnostics", "effective-sample-size-adjusted uncertainty", "optional exploratory between-replica summaries", "population-validity status", "failed-gate evidence"), ("Incompatible sampling methods cannot be pooled without an explicit calibration model.", "Autocorrelation, ESS, and block analyses are diagnostics rather than proof of independent sampling.", "Replica agreement and leave-one-replica-out are not acceptance measures.", "Population validity requires all declared non-replica gates, not merely technical execution."), status="experimental"),
    _module("integrated_comparison", "Integrated comparative analysis", "reporting", "14", "Extract prespecified RFC-6901 values from validated module reports while preserving raw values, failures, source statuses, and interpretation types without hidden aggregation.", ("project manifest", "supported module outputs", "entry IDs and value pointers", "interpretation types", "failure policy"), ("integrated raw-value table", "source-module status table", "upstream issues", "explicit no-aggregation contract"), ("Exploratory prioritization must remain separate from inferential claims.", "The current base integrator does not calculate composite scores.", "A shared table does not change the evidentiary status of its rows."), status="experimental"),
    _module("alternative_clustering", "Alternative clustering and validation", "md", "8A", "Run distinctly labeled PAM, Minkowski-weighted PAM, Ward, Gaussian and variational mixtures, affinity propagation, mean shift, and quality-threshold clustering while scanning declared parameters; predictive or medoid families can fit deterministic replica-balanced samples and assign selected partitions to every source observation, while Ward and quality-threshold are skipped unless an exact complete fit is affordable and fully assigned.", ("tICA, common PCA, or declared trajectory features", "algorithm-specific parameter grids", "one planner-selected fit budget or optional sensitivity budgets", "silhouette and algorithm resource gates"), ("all parameter-sweep or explicit skip records", "sampled-fit identities and coverage", "all-frame selected assignments and populations where supported", "exact or model-based extension identity", "medoids/centers/weights", "silhouette, Calinski-Harabasz, Davies-Bouldin, and cross-budget adjusted-Rand diagnostics"), ("Different algorithms are not treated as interchangeable.", "Ward and quality-threshold never receive approximate all-frame extensions.", "An all-frame assignment from another sampled fitted model is not equivalent to refitting the algorithm on all frames.", "Geometric separation and budget agreement do not establish metastability, convergence, or kinetics.", "PaLD community structure is a separate module and is not ranked as a conventional partition."), status="experimental"),
    _module("pald_community_analysis", "Partitioned Local Depth community analysis", "md", "8P", "Calculate PaLD cohesion, local depth, mutual-cohesion networks, the universal strong-tie threshold, connected strong-tie communities, core and boundary observations, and an optional separately labeled sampled-community MSM on one regular replica-member-balanced sample.", ("tICA, common PCA, or declared trajectory features", "strict cubic observation gate", "replica, member, segment, frame, and physical-time identities", "optional Markov-model settings"), ("cohesion and mutual-cohesion matrices", "local-depth values", "strong-tie threshold and graph", "community labels and cores", "intercommunity ties", "optional sampled PaLD-community MSM"), ("PaLD is a community-network analysis rather than a conventional all-frame clustering method.", "Equivalent oligomer members are separate observations but not independent replicas.", "The cubic calculation requires bounded regular sampling.", "Cohesion and communities do not establish kinetics, pathways, metastability, causality, or convergence.", "Any community MSM is reported separately and never competes for best-clustering selection."), status="experimental"),
    _module("information_dynamics", "Directional and higher-order information dynamics", "md", "5D", "Calculate segment-safe finite-bin transfer entropy, source-at-t to target-at-t-plus-lag cross-correlation, third-order coskewness, and displacement-propagator observables with explicit lag and resource gates.", ("declared feature segments or vector displacements", "lag/bin settings", "resource gates"), ("source-to-target transfer-entropy matrix", "directional lagged cross-correlation matrix", "coskewness tensor", "normalized propagator"), ("Finite-bin estimates require sensitivity analysis.", "Directional dependence does not establish causal mechanism.", "Lag pairs never cross segments."), status="experimental"),
    _module("perturbation_response_dynamics", "Perturbation-response DFI and DCI", "md", "6D", "Calculate dynamic flexibility and functional-site dynamic coupling indices from per-system common-PCA score covariances mapped into the retained shared Cartesian subspace, using reproducible random unit-force perturbations.", ("common PCA basis and per-system projections", "zero-based functional-site node indices", "force-sampling and explained-variance gates"), ("target-by-source response matrices", "DFI and percentile profiles", "functional-site DCI and percentile profiles", "reference-system differences", "retained-subspace provenance"), ("Residue interpretation requires one declared representative node per residue.", "Results require PCA-dimensionality, force-count, functional-site, alignment, mapping, and sampling sensitivity analysis.", "Frame-pooled covariance is not replica-level uncertainty.", "Dynamic coupling does not establish causality, pathway, mechanism, or scientific validity."), status="experimental"),
    _module("trajectory_reweighting", "Frame-aligned trajectory reweighting", "md", "7W", "Normalize externally derived per-frame log weights with exact trajectory-identity joins, stable log-sum-exp arithmetic, per-system weighted common-PCA moments, and declared Kish-ESS, Kish-ratio, and maximum-weight reliability gates.", ("common PCA projections with frame identities", "external log weights with matching system/replica/segment/member/frame identities", "declared reliability gates"), ("normalized per-frame weights", "Kish and entropy effective sample sizes", "weight-concentration diagnostics", "weighted common-PCA moments", "reweighting validity status"), ("The module consumes weights and does not infer bias potentials, MBAR free energies, or experimental-restraint multipliers.", "Weight-only ESS does not remove trajectory autocorrelation or prove phase-space overlap.", "Passing gates does not silently authorize biased FES conversion or establish scientific validity."), status="experimental"),
    _module("correlation_networks", "Correlation networks and profile clustering", "md", "5R", "Convert signed DCCM or reference-difference matrices into thresholded networks with edges, degree, strength, components, and local clustering coefficients; optionally cluster correlation profiles with the reference HDBSCAN package using declared signed-profile or absolute-similarity distances.", ("complete DCCM matrices", "absolute threshold", "negative-edge policy", "optional HDBSCAN profile-clustering settings"), ("signed edge table", "node metrics", "connected components", "optional canonical profile-cluster labels and noise assignments"), ("Network topology and profile clustering are threshold- and parameter-sensitive.", "Correlation edges and clusters are not direct physical interactions or causal links.", "The optional HDBSCAN dependency must be installed separately."), status="experimental"),
    _module("allosteric_pathways", "Trajectory-derived contact-occupancy pathways", "md", "5A", "Build per-system residue contact occupancies directly from selected trajectory frames, transform retained occupancies to negative-log path distances, enumerate declared source-to-sink shortest-path multiplicity and participation, calculate weighted betweenness, and optionally combine it with a separately derived displacement-dependency factor.", ("accepted trajectories and topology mappings", "one representative atom per residue", "declared source and sink node sets", "contact, sequence-separation, and occupancy thresholds", "optional explicit external-network override"), ("trajectory-derived contact edge tables", "all-equal-shortest-path counts and representative paths", "node and edge path participation", "weighted betweenness centrality", "optional local dependency and combined prioritization scores"), ("Physical contacts and statistical dependencies remain separate channels; dependency never creates an edge.", "Negative-log occupancy distance is a persistence cost, not time, energy, or causal information flow.", "Representative-atom cutoff, sequence exclusion, occupancy threshold, endpoint, and sampling sensitivity are required.", "The local dependency factor is code-defined and does not claim equivalence to an external SenseNet implementation.", "Pathways and prioritization scores do not establish mechanism or scientific validity."), status="experimental"),
    _module("energetic_network_embeddings", "Residue interaction-energy network embeddings", "md", "12E", "Reproduce the Cowan/Thayer cpptraj-pairwise protein-only workflow from atom-order-matched Amber PRMTOP, CHARMM PSF plus parameter/stream files, or a serialized OpenMM System: direct nonperiodic electrostatic and Lennard-Jones atom-pair energies, absolute residue aggregation, local edge normalization, electrostatic heat kernels, deterministic per-frame PCA, and residue-wise Wasserstein comparisons.", ("accepted made-whole trajectories", "PDB/GRO atom identities", "Amber PRMTOP/PARM7, CHARMM PSF plus PRM/PAR/STR, or one standard-NonbondedForce OpenMM System XML", "explicit bond graph for cpptraj-style exclusions", "at least two complete common protein residues", "frame and all-pairs resource gates"), ("protein-only residue-pair interaction-energy networks", "electrostatic heat kernels", "per-frame three-component embeddings", "pairwise-system residue Wasserstein rankings", "VDW-negligibility diagnostic"), ("The network is not a unique decomposition of the reciprocal-space PME contribution or the complete simulation energy.", "CHARMM NBFIX is honored; OpenMM custom nonbonded expressions fail closed rather than being guessed.", "Raw GROMACS TPR extraction is not implemented; GROMACS-derived systems can use serialized OpenMM System XML when representable by one standard NonbondedForce.", "Solvent, ions, nucleic acids, ligands, mutations, and atom-incomplete residues are excluded; no solvent-inclusive or signed-energy extension is implemented.", "Absolute-energy aggregation discards favorable-versus-unfavorable sign.", "Per-frame PCA and summed marginal Wasserstein distances inherit the published supplement's axis and dependence limitations.", "Residue rankings are descriptive and do not establish affinity, causality, mechanism, or allostery."), status="experimental"),
    _module("multivalent_molecular_bridges", "Multivalent molecular-bridge networks", "md", "12B", "Identify supported ions, recognized waters, or explicitly named ligand and cosolvent residues that simultaneously contact multiple solute residues; retain frame-level bridge hyperedges, pairwise residue-network projections, multiplicity distributions, and segment-safe boundary-censored bridge residence events.", ("accepted trajectories and topology identities", "configured mediator classes and optional residue names", "solute residue classes and atom-element filters", "mediator-specific contact cutoffs", "frame and sparse-output resource gates"), ("frame-level mediator-to-residue hyperedges", "mediator and mediator-type bridge occupancies", "multiplicity distributions", "segment-safe residence events", "pairwise projected residue edges"), ("Distance-defined bridges do not establish binding affinity, energetic stabilization, phase separation, or mechanism.", "Recognized-water bridges are oxygen-proximity observations; hydrogen-bond chemistry remains a separate module.", "Pairwise projection expands a k-residue hyperedge into k choose 2 edges and must not replace the retained hyperedge.", "Subsampled selected-observation runs are not continuous-time lifetimes.", "Cutoff, protonation, atom selection, and mediator-definition sensitivity are required."), status="experimental"),
    _module("hydration_density_channels", "Aligned hydration and ion-density channels", "md", "12D", "Accumulate reference-aligned three-dimensional water and ion frame occupancy on an explicit bounded grid, retain exact frame-to-component identities, compare common-grid densities across systems, and identify connected boundary-reaching high-occupancy geometric channel candidates.", ("accepted trajectories and topology identities", "alignment and solute-extent selections", "configured water and ion identities", "grid, occupancy, component, and resource gates"), ("species-resolved voxel occupancy", "two-dimensional density projections", "connected density components", "geometric channel-candidate labels", "exact frame-level component fingerprints", "pairwise common-grid differences"), ("This spatial analysis supplements rather than replaces RDF, bridge, and interaction-fingerprint definitions.", "Boundary-reaching components are geometric channel candidates, not evidence of diffusion, flux, permeability, free energy, or mechanism.", "Alignment, grid, occupancy threshold, species identity, and frame-selection sensitivity are required.", "Frame occupancies are descriptive and are not independent-replica uncertainty."), status="experimental"),
    _module("ensemble_pocket_dynamics", "Ensemble pocket dynamics", "md", "12P", "Accumulate reference-aligned geometric pocket-voxel frequencies, define recurrent connected spatial regions after all selected frames, retain exact frame identities and observed representatives, and compare region occupancy across systems; an optional legacy backend tracks discrete frame-pocket identities.", ("accepted trajectories and topology identities", "alignment and solute-heavy selections", "grid and geometric enclosure settings", "frequency-region thresholds and resource gates"), ("voxel frequency maps", "recurrent pocket regions", "per-frame region volumes", "lining-residue occurrence summaries", "observed representative-frame identities", "pairwise occupancy differences"), ("The native geometry screen does not predict druggability, ligand affinity, binding free energy, or opening kinetics.", "The frequency-map backend is not an fpocket or MDpocket alpha-sphere reimplementation.", "Region definitions are threshold-sensitive and require grid, atom-selection, frequency, and frame-selection sensitivity analysis.", "The legacy discrete-tracking backend remains optional because transient identity assignment is threshold-sensitive.", "Solvent occupancy is provided separately by the hydration-density module and is not treated as pocket wall material.", "Frame persistence is descriptive and is not independent-replica uncertainty."), status="experimental"),
    _module("interaction_fingerprints", "Chemically typed interaction fingerprints", "md", "12F", "Join exact frame identities from direct hydrogen bonds, one-water bridges, ion coordination, ion-atmosphere shells, multivalent mediator bridges, and aligned hydration-density components into one sparse chemically typed fingerprint with explicit source missingness and pairwise-complete co-occurrence statistics.", ("one or more complete supported interaction or hydration-density reports", "exact system/replica/segment/source-frame identities", "feature and pair resource gates"), ("typed feature dictionary", "frame-level sparse fingerprints with source availability", "source-specific occupancies", "pairwise-complete co-occurrence, conditional probability, Jaccard, and phi tables"), ("Missing upstream frames are never interaction-negative observations.", "Feature and interaction chemistry or spatial definitions are inherited from source modules and require their sensitivity analyses.", "Co-occurrence is descriptive association, not energetic coupling, causality, or mechanism.", "Frame counts are not independent-replica uncertainty."), status="experimental"),
    _module("spatial_interaction_ensembles", "Spatial interaction superfeatures", "md", "12S", "Convert extractable direct-hydrogen-bond and ion-coordination fingerprint endpoints into exact receptor-aligned partner-coordinate ensembles, summarize their three-dimensional spread, and test deterministic NANI spatial partitions with observation, separation, recurrence, and replica-support gates.", ("complete interaction-fingerprint report", "accepted trajectories and topology identities", "reference structure and declared alignment selection", "observation, recurrence, and exact-mode resource gates"), ("spatial superfeature dictionary", "exact frame-aligned partner-coordinate observations", "centroid, covariance, principal-axis, and radius summaries", "gated spatial mode candidates", "pairwise system spatial differences", "explicit unsupported-feature inventory"), ("The module supplements rather than replaces binary fingerprints, RDFs, bridges, hydration density, or persistence analyses.", "Only fingerprint types exposing exact partner atoms are spatialized; unsupported types are explicitly reported.", "Alignment and atom-definition sensitivity are required, and multiple points from one frame are not independent samples.", "Spatial mode candidates are not binding states, free-energy basins, kinetics, metastability, affinity, causality, or mechanism."), status="experimental"),
    _module("interaction_persistence", "Temporal persistence of interaction fingerprints", "md", "12T", "Convert exact-frame chemically typed fingerprints into segment-safe continuous and explicitly gap-tolerant persistence events with physical-time durations, complete-event gates, and left/right boundary censoring while preserving source-specific missingness.", ("complete interaction-fingerprint report", "source-module availability on every fingerprint frame", "physical segment timing", "gap, interval-regularity, complete-event, feature, and event-record gates"), ("feature/system persistence events", "complete and boundary-censored duration distributions", "zero-gap primary and gap-tolerant sensitivity summaries", "complete-event sufficiency status"), ("Missing source observations are never treated as interaction-negative frames.", "Durations describe persistence across saved and evaluated snapshots; behavior between observations is unobserved.", "Gap-tolerant persistence is a sensitivity and never replaces the zero-gap primary definition.", "Occupancy and persistence do not establish binding free energy, affinity, causality, or mechanism."), status="experimental"),
    _module("trajectory_features", "Reusable trajectory feature extractors", "md", "6F", "Extract declared Cartesian, fluctuation, center-of-mass, center-of-geometry, pair-distance, group min/mean/max distance, minimum-mean group distance, COM/COG distance, and mass-weighted principal-axis features with frame identities and periodic reconstruction.", ("accepted trajectories", "topologies", "atom-index feature definitions"), ("segment-resolved feature records", "distance statistics and selected atom-pair identities", "centers", "principal moments and relative axes"), ("Feature and group-aggregation definitions must be frozen before comparison.", "Project-specific physical meanings belong in manifests, not package source."), status="experimental"),
    _module("scalar_feature_distributions", "Scalar feature histograms and residence runs", "md", "6H", "Build explicit, Scott, Freedman-Diaconis, or Rice histograms for declared scalar trajectory features and calculate segment-safe, boundary-censored residence runs without joining discontinuous trajectories.", ("trajectory feature records", "feature/value identity", "binning rule and gates", "observation gate"), ("raw histogram counts and frame assignments", "automatic-rule width evidence", "segment-safe residence runs", "complete and censored run summaries"), ("Histogram and residence estimates require bin and stride sensitivity.", "Residence runs never cross declared segment boundaries.", "Histogram occupancy and residence do not establish convergence, metastability, kinetics, or mechanism."), status="experimental"),
    _module("scalar_threshold_states", "Scalar threshold states", "md", "6T", "Convert declared scalar trajectory features into explicit two-state definitions with threshold sensitivity, system/replica populations, segment-safe transitions, and boundary-censored residence runs.", ("trajectory feature records", "feature/value identity", "primary and sensitivity thresholds", "state labels"), ("frame state assignments", "system/replica population comparisons", "threshold sensitivity", "segment-safe transitions and residence"), ("Thresholds must be frozen before comparative outcome review.", "Frame counts require correlation-aware uncertainty and physical-time conversion.", "A distance threshold is an operational binding definition, not affinity or binding free energy."), status="experimental"),
    _module("hydrogen_bond_patterns", "Hydrogen-bond pattern clustering", "md", "11P", "Encode explicit frame-level bond IDs as binary patterns and cluster them using Jaccard PAM or the optional reference HDBSCAN implementation.", ("explicit hydrogen-bond observations", "bond-ID dictionary", "clustering settings"), ("binary pattern matrix", "Jaccard distances", "cluster labels and medoids/noise"), ("Patterns inherit the upstream hydrogen-bond definition.", "Clusters are descriptive and do not establish energetic or mechanistic importance."), status="experimental"),
    _module("representative_structures", "Average and observed representative structures", "md", "8S", "Calculate arithmetic mean coordinates, the observed frame closest to the mean, the medoid, and central observed frames for a prealigned ensemble.", ("aligned common-atom coordinates", "optional frame weights"), ("labeled arithmetic mean", "closest observed frame", "medoid", "central-frame set"), ("Arithmetic means need not be chemically valid structures.", "Inputs must already share a validated atom order and alignment basis."), status="experimental"),
    _module("rmsf_permutation_inference", "RMSF permutation inference", "md", "13R", "Compare independent replica- or time-block RMSF profiles with exact or seeded Monte Carlo label permutations and max-T familywise adjustment.", ("group-resolved RMSF profiles", "exchangeability declaration", "permutation settings"), ("mean-difference profile", "pointwise p-values", "max-T adjusted p-values"), ("Rows, not frames, are the exchangeable units.", "Exchangeability and multiplicity choices require scientific justification."), status="experimental"),
)


_BY_ID = {module.module_id: module for module in MODULES}
if len(_BY_ID) != len(MODULES):
    raise RuntimeError("Duplicate module IDs in registry")
validate_registry_coverage(set(_BY_ID))


def list_modules() -> List[ModuleSpec]:
    return list(MODULES)


def get_module(module_id: str) -> ModuleSpec:
    try:
        return _BY_ID[module_id]
    except KeyError as exc:
        raise KeyError(f"Unknown analysis module: {module_id}") from exc
