"""Authoritative registry of intended and implemented analysis modules.

The registry is deliberately explicit. A module is not implemented merely because it
appears here; status must remain ``planned`` until reviewed code and tests exist.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

from .reporting import DataclassRecordMixin


VALID_STATUSES = {"planned", "experimental", "supported", "deprecated"}
VALID_CATEGORIES = {"core", "md", "reporting"}


@dataclass(frozen=True)
class ModuleSpec(DataclassRecordMixin):
    module_id: str
    title: str
    category: str
    stage: Optional[str]
    status: str
    summary: str
    required_inputs: Tuple[str, ...]
    outputs: Tuple[str, ...]
    scientific_limits: Tuple[str, ...]
    first_supported_version: Optional[str] = None

    def __post_init__(self) -> None:
        if self.status not in VALID_STATUSES:
            raise ValueError(f"Invalid module status {self.status!r}")
        if self.category not in VALID_CATEGORIES:
            raise ValueError(f"Invalid module category {self.category!r}")
        if not self.module_id or any(char.isspace() for char in self.module_id):
            raise ValueError("module_id must be nonempty and contain no whitespace")
        if self.status == "supported" and not self.first_supported_version:
            raise ValueError("supported modules require first_supported_version")

def _module(
    module_id: str,
    title: str,
    category: str,
    stage: Optional[str],
    summary: str,
    required_inputs: Tuple[str, ...],
    outputs: Tuple[str, ...],
    scientific_limits: Tuple[str, ...],
    status: str = "planned",
) -> ModuleSpec:
    return ModuleSpec(
        module_id=module_id,
        title=title,
        category=category,
        stage=stage,
        status=status,
        summary=summary,
        required_inputs=required_inputs,
        outputs=outputs,
        scientific_limits=scientific_limits,
    )


MODULES: Tuple[ModuleSpec, ...] = (
    _module("provenance_manifest", "Provenance and immutable manifests", "core", "1", "Validate project, system, output, and publication-lock manifests; compile explicit units, selections, and system/replica/segment identities; and produce deterministic input inventories with optional SHA-256 hashes.", ("project configuration", "system manifest", "declared units", "named selections"), ("validated manifests", "compiled analysis context", "context signature", "input inventory", "input hashes"), ("Provenance records technical lineage; it does not establish trajectory readability, convergence, population meaning, or scientific validity.",), status="experimental"),
    _module("preflight_inventory", "Trajectory and topology preflight", "md", "1", "Inspect supported topology and trajectory metadata, compare atom counts, and check declared DCD segment continuity without loading coordinates.", ("validated system manifest", "topologies", "trajectories"), ("format-aware preflight report", "technical issues", "input metadata"), ("Current DCD support reads declared header metadata rather than coordinate records or actual frame counts.", "Passing preflight does not demonstrate chemical correctness, equilibration, convergence, adequate sampling, or scientific validity."), status="experimental"),
    _module("common_atom_mapping", "Validated common-atom mapping", "core", "1", "Create deterministic PDB/GRO atom maps across variants using explicit strict or position identity, atom selection, coverage gates, exclusions, and a stable mapping signature.", ("reference topology", "one or more target topologies", "mapping policy", "selection", "coverage threshold"), ("common atom map", "mapping signature", "coverage", "mapping exclusions", "mutation warnings"), ("Identity mapping does not perform sequence or structural alignment.", "The position policy ignores residue-name substitutions and requires prevalidated numbering correspondence.", "Weakly homologous systems must not be forced onto a whole-protein common basis."), status="experimental"),
    _module("structural_integrity_qc", "Structural integrity and unusual-state QC", "md", "2", "Stream supported coordinates and apply explicit readability, atom-count, finite-coordinate, extent, displacement, peptide-continuity, omega, C-alpha chirality, element-radius clash, and declared covalent-link gates.", ("validated project context", "trajectory segments", "topology", "explicit QC thresholds", "optional declared covalent links"), ("replica/segment QC report", "technical issues", "chemical-integrity examples", "quarantine evidence"), ("Chemical checks require explicit settings and connectivity-aware periodic reconstruction for production trajectories.", "The conservative steric screen excludes same-residue pairs and does not replace specialized cofactor, metal, or force-field validation.", "Thresholds must be declared before comparative outcome review."), status="experimental"),
    _module("replica_rmsd_rg", "Replica-resolved RMSD and radius of gyration", "md", "3", "Stream replica/segment trajectories, fit a declared common selection to an explicit reference, and calculate unweighted RMSD plus mass-weighted radius of gyration with mapping and coverage evidence.", ("validated project context", "PDB/GRO topology", "supported trajectories", "reference structure", "named selections", "mapping policy", "coverage threshold"), ("replica/segment timeseries", "metric summaries", "mapping signatures", "coverage and limitation report"), ("RMSD is primarily stability and QC evidence, not functional importance.", "Periodic molecules must be made whole before this experimental implementation can support wrapped production trajectories.", "Frame indices do not become physical time without an explicit trajectory timing contract.", "Technical completion does not establish equilibration, convergence, adequate sampling, or scientific validity."), status="experimental"),
    _module("pooled_rmsf", "Replica-pooled RMSF with uncertainty", "md", "4", "Fit a globally common atom basis and stream frame-pooled RMSF while retaining separate per-replica and explicit frame-block estimates with sample SD/SEM only when estimable.", ("validated project context", "PDB/GRO topologies", "supported trajectories", "reference structure", "named alignment and analysis selections", "mapping and coverage policy", "frame-block specification"), ("frame-pooled RMSF profile", "per-replica RMSF profiles", "time-block profiles", "between-replica and block summaries", "RMSF-in-B-factor PDB and VMD NewCartoon export", "mapping and lineage evidence"), ("Frames are not independent uncertainty units.", "Frame-pooled and replica-balanced RMSF are distinct estimators and must remain labeled.", "Time-block estimates are convergence diagnostics, not automatically independent replicates.", "RMSF stored in a PDB B-factor field remains RMSF in angstrom and is not a crystallographic B factor.", "Periodic molecules must be made whole before wrapped production trajectories can be interpreted.", "Technical completion does not establish equilibration, convergence, adequate sampling, or scientific validity."), status="experimental"),
    _module("dccm", "Dynamic cross-correlation", "md", "5", "Stream fitted coordinates into replica and frame-pooled Cartesian displacement cross-correlation matrices on one global atom basis, with explicit zero-variance and quadratic-size gates plus reference-system differences.", ("validated project context", "PDB/GRO topologies", "supported trajectories", "reference structure and system", "named selections", "mapping and coverage policy", "variance, size, frame, and stride gates"), ("per-replica DCCMs", "system-pooled DCCMs", "reference-system difference matrices", "undefined-entry and off-diagonal summaries", "mapping and lineage evidence"), ("Generalized correlation and mutual information require separately labeled methods.", "Null zero-variance entries must not be interpreted as zero correlation.", "Frame-pooled matrices are not replica-level uncertainty estimates.", "Correlation does not establish causality, directionality, mechanism, or significance.", "Periodic molecules must be made whole before wrapped production trajectories can be interpreted."), status="experimental"),
    _module("generalized_correlation_and_information", "Generalized correlation and mutual information", "md", "5N", "Estimate symmetric nonlinear dependence between declared common-PCA features using explicit quantile histograms, natural-log mutual information, normalized mutual information, and the scalar generalized-correlation transform.", ("common PCA projections", "selected feature indices", "bin-count and observation gates"), ("marginal entropies", "mutual-information matrices", "normalized mutual-information matrices", "generalized-correlation matrices", "feature lineage"), ("Histogram information estimates require bin-count and sample-size sensitivity analysis.", "The current provider uses scalar common-PCA features; residue-vector and distance-feature providers remain extensions.", "Symmetric dependence does not establish direction, causality, or mechanism."), status="experimental"),
    _module("individual_pca", "Individual-replica PCA", "md", "6", "Fit each replica to an explicit reference and calculate a separate population-covariance PCA basis, deterministic component orientation, variance accounting, and physical-time or sample-index projections with feature, frame, periodicity, and solver gates.", ("validated project context", "PDB/GRO topologies", "supported trajectories", "reference structure", "named selections", "mapping and coverage policy", "feature, frame, component, and stride gates"), ("per-replica means", "eigenvalues and explained variance", "component loadings", "physical-time or sample-index projections", "solver and mapping evidence"), ("Coordinates from independently fitted PCA bases are not directly comparable.", "Frames are not independent uncertainty units.", "Near-degenerate subspaces require sensitivity analysis.", "Periodic molecules must be made whole before wrapped production trajectories can be interpreted."), status="experimental"),
    _module("common_pca", "Common-atom shared-basis PCA", "md", "6", "Fit one global common-atom PCA basis across all declared replicas using an explicit frame-weighted or equal-replica population mixture and an exact dense or gated leading-component solver selected from feature dimensions, then project the declared trajectory frames onto that shared basis and report reference-system differences.", ("validated project context", "PDB/GRO topologies", "supported trajectories", "reference structure and system", "named selections", "mapping and coverage policy", "basis weighting", "feature-aware solver and sample-matrix limits", "independent basis-fit and projection frame contracts"), ("global mean and common atom basis", "eigenvalues and explained variance", "component loadings", "shared projections", "replica/system projection summaries", "reference-system mean differences", "solver residual and resource evidence"), ("Unequal sampling and atom-map choices require separate sensitivity runs.", "Basis subsampling is computational and does not prove scientific convergence.", "Frames are not independent uncertainty units.", "Near-degenerate subspaces require subspace-level comparison.", "Periodic molecules must be made whole before wrapped production trajectories can be interpreted."), status="experimental"),
    _module("time_lagged_independent_component_analysis", "Time-lagged independent component analysis", "md", "6K", "Fit reversible, segment-safe TICA components to declared common-PCA features using symmetrized endpoint and lagged covariances, covariance-rank gates, and explicit physical lag time.", ("unbiased-MD common PCA projections", "selected PCA components", "lag and covariance settings", "segment identities and physical timing"), ("instantaneous and lagged covariances", "TICA eigenvalues and loadings", "segment-resolved projections", "implied timescale diagnostics", "numerical residuals"), ("Lag pairs never cross segment boundaries.", "Current kinetic interpretation requires unbiased MD and one common evaluated physical-time interval.", "TICA modes and timescales require lag, feature, stationarity, and convergence sensitivity analysis."), status="experimental"),
    _module("pca_fes_basins", "PCA free-energy surfaces and basin populations", "md", "7", "Construct declared two-dimensional histogram grids using explicit counts or independently applied Scott, Freedman-Diaconis, or Rice rules; preserve raw counts while scanning declared Gaussian smoothing widths; calculate deterministic steepest-occupancy watershed basins, minima, frame assignments, smoothing agreement, basin silhouette diagnostics, and replica/segment-block population tables; convert density to relative free energy only for unweighted unbiased MD with declared temperature.", ("common PCA projections", "temperature for unbiased MD", "sampling/weight model", "explicit bins or automatic binning rule and gates", "declared smoothing widths", "grid and basin thresholds"), ("relative FES or nonthermodynamic occupancy grids", "raw counts and bin-selection evidence", "smoothing-resolved minima and basins", "frame assignments", "exact or seeded estimated basin silhouette diagnostics", "replica and block population tables", "cross-smoothing agreement"), ("Raw AI-ensemble counts are labeled occupancy and are never converted to thermodynamic free energy.", "Biased or enhanced sampling fails closed until a validated reweighting model is implemented.", "Basin silhouette is secondary PCA-plane separation evidence and never defines minima or selects smoothing.", "Histogram, smoothing, and basin definitions require sensitivity analysis and do not establish metastability or kinetics."), status="experimental"),
    _module("clustering_kmeans", "KMeans clustering", "md", "8", "Select complete tICA or common-PCA partitions using a declared k grid, KMeans++ seeds, convergence and occupancy gates, exact or deterministic seeded full-partition silhouette evaluation, and adjusted-Rand seed stability.", ("tICA or common PCA features", "component selection", "cluster grid", "random seeds", "occupancy, size, and silhouette resource gates"), ("complete assignments", "centers", "per-seed diagnostics", "exact-or-estimated silhouette provenance", "stability selection evidence"), ("A high silhouette score and seed stability do not establish physical metastability, convergence, or kinetics.", "Euclidean KMeans favors convex clusters in the declared standardized or raw feature space."), status="experimental"),
    _module("clustering_hdbscan", "HDBSCAN sensitivity clustering", "md", "8", "Use the optional reference hdbscan package to scan density parameters while reporting noise, retained coverage, retained-only silhouette, and complete assignment identities.", ("common PCA features", "component selection", "minimum-cluster-size and minimum-samples grids", "hdbscan optional dependency"), ("noise-aware assignments", "retained coverage", "cluster-size and parameter diagnostics", "reference-package provenance"), ("Noise-excluding clusters are a sensitivity analysis and are not complete kinetic assignments.", "Silhouette must be read together with retained coverage.", "The optional hdbscan dependency must be installed separately."), status="experimental"),
    _module("clustering_imwkmeans", "Intelligent Minkowski weighted KMeans", "md", "8", "Provide a deterministic iMWK-Means implementation with Lp centers, cluster-specific feature weights, and k/p/initialization sensitivity scans.", ("common PCA features", "component selection", "k and p grids", "initialization ranks", "occupancy and size gates"), ("complete assignments", "Lp centers", "cluster feature weights", "grid and initialization diagnostics"), ("Ordinary KMeans must not be relabeled as iMWK-Means.", "Feature weights are descriptors of the fitted partition, not mechanistic importance scores.", "Partitions do not establish metastability, convergence, or kinetics."), status="experimental"),
    _module("representative_frames", "Representative frames for clusters and PCA basins", "md", "8R", "Select one or more observed frames nearest each declared KMeans center or PCA-basin root with deterministic identity tie-breaking and no coordinate-file mutation.", ("complete KMeans assignments or PCA-FES basin assignments", "state centers", "representative-count and resource gates"), ("state-resolved representative frame locators", "center distances", "selection and upstream lineage"), ("Representatives are observed frames, not arithmetic average structures.", "Selection inherits every feature, scaling, clustering, and basin-definition choice from its source module.", "A representative frame does not establish metastability, convergence, mechanism, or scientific validity."), status="experimental"),
    _module("state_coordinate_exports", "Immutable state trajectories and structures", "md", "8E", "Materialize state-resolved multi-frame PDB or XYZ trajectories and observed representative PDB structures from declared FES or clustering assignments, using periodic reconstruction and an atomic fail-if-present output directory.", ("complete FES or clustering assignments", "declared output ID and format", "frame and state resource gates", "validated topology and trajectory identities"), ("state/system/replica trajectory files", "observed representative PDB structures", "checksummed export manifest", "source-frame lineage"), ("Source trajectories are never edited or overwritten.", "Unlike system or replica topologies are never silently combined.", "Exported subsets and representatives do not establish metastability, convergence, kinetics, mechanism, or scientific validity."), status="experimental"),
    _module("markov_state_models", "Markov-state models", "md", "9", "Build segment-safe transition models for every enabled complete clustering partition, select the best clustering model by kinetic validation, retain a separately reported FES-basin model, and report explicitly enabled noise-censored HDBSCAN only as a conditional sensitivity; Ward and quality-threshold are omitted unless they provide exact complete assignments over every observation; scan lag times, estimators, implied-timescale stability, Chapman-Kolmogorov consistency, time-blocked VAMP validation, and block-bootstrap uncertainty.", ("complete enabled clustering assignments", "optional noise-censored HDBSCAN sensitivity assignments", "primary PCA-FES basin assignments", "physical frame timing", "segment identities", "lag, VAMP, CK, and bootstrap settings"), ("best geometric clustering", "best kinetically validated complete clustering model", "separate FES state model", "separate HDBSCAN core MSM sensitivity", "count and transition matrices", "stationary distributions and reversible implied timescales", "connectivity, CK, VAMP-E, implied-timescale stability, and block-bootstrap diagnostics"), ("Transitions are never joined across segment, noise-gap, or bootstrap-block boundaries.", "Noise-censored HDBSCAN is a conditional sensitivity and never enters primary MSM selection.", "Ward and quality-threshold are skipped unless their exact fit assigns every observation.", "The clustering and FES state definitions are both reported and are not treated as interchangeable.", "Rates and pathways are not valid until sampling, lag, connectivity, population, and convergence gates pass.", "Technical completion does not establish a valid kinetic model."), status="experimental"),
    _module("dihedral_distributions", "Backbone and side-chain dihedral distributions", "md", "10", "Stream declared phi, psi, omega, and conventional protein chi1-chi5 torsions with reference-distance peptide-link gates and residue-resolved circular summaries.", ("accepted trajectories", "PDB/GRO topology", "declared torsion types", "reference peptide-link threshold"), ("residue and replica circular statistics", "angular histograms", "definition and periodicity diagnostics"), ("Local mutation effects and distal effects must be distinguished.", "Nonstandard residues require an explicit future torsion adapter rather than guessed atom names.", "Circular distributions do not establish convergence or significance."), status="experimental"),
    _module("hydrogen_bonds", "Hydrogen-bond occupancies", "md", "11", "Evaluate explicitly indexed donor-hydrogen-acceptor features using declared distance and angle rules, with optional KMeans-state conditioning and fail-closed water/periodicity policies.", ("accepted trajectories", "topology with explicit hydrogens", "indexed hydrogen-bond features", "distance, angle, water, and conditioning rules"), ("feature occupancies", "mean geometry", "optional cluster-conditioned occupancies", "definition and periodicity diagnostics"), ("Definitions and inclusion rules must accompany every occupancy result.", "The current implementation excludes water-mediated bonds.", "Occupancy does not establish energetic or mechanistic importance."), status="experimental"),
    _module("hydrogen_bond_discovery", "Topology-template hydrogen-bond discovery", "md", "11D", "Automatically enumerate a frozen direct donor-hydrogen-acceptor dictionary from standard protein/nucleic-acid chemistry templates and explicit connectivity, with auditable provisional fallback for untemplated ligands; retain an explicit atom-index mode for publication locks, outcome-independent common-candidate harmonization for homologous systems, and optional chunked or fixed-width packed sparse output for large candidate universes.", ("accepted trajectories", "explicit connectivity", "automatic interaction scope or publication-locked explicit features", "primary and sensitivity geometry rules"), ("candidate bond dictionary", "dense, sparse-list, or packed sparse frame-by-bond observations", "observed geometry", "directly readable primary occupancies", "exact packed sensitivity occupancies", "chemistry and harmonization provenance"), ("Automatic chemistry cannot repair missing or incorrect protonation, tautomer, formal charge, or ligand bond order.", "Common-candidate harmonization excludes system-specific chemical candidates from a comparative matrix before coordinates are evaluated; retain separate per-system discovery for those features.", "Packed sparse frames use single-precision geometry and preserve exact cutoff membership; they do not imply greater physical precision than the source coordinates.", "Packed sensitivity occupancies are exact nonzero count tables; absent candidate-cutoff records are evaluated zeros under the report's explicit-zero contract.", "This direct-bond module excludes water-mediated paths, which have a separate contract.", "Occupancy does not establish energetic or mechanistic importance."), status="experimental"),
    _module("hydrogen_bond_comparison", "Grouped chemical-identity hydrogen-bond comparison", "md", "11C", "Compare exactly two technically complete sparse direct-hydrogen-bond discovery reports after collapsing connectivity-equivalent donor hydrogens into one donor-heavy-atom/acceptor-heavy-atom event per frame; align nonidentical topologies only through explicit project-supplied chemical-homolog mappings.", ("two sparse hydrogen-bond discovery reports", "identical interaction scope and cutoff definition", "condition labels", "optional explicit chemical-homolog mappings"), ("equal-replica and pooled grouped occupancies", "condition occupancy differences", "per-replica evidence", "mapping and source-report provenance"), ("Homolog mappings are chemical assertions and are never inferred by the implementation.", "Equal-replica descriptive means do not establish independent sampling or convergence.", "Occupancy differences do not establish energy, affinity, causality, or mechanism."), status="experimental"),
    _module("water_mediated_hydrogen_bond_networks", "Water-mediated hydrogen-bond networks", "md", "11W", "Discover one-water solute bridges from automatic solute chemistry and connectivity-backed water identity, evaluate edges with a spatial cell list and exact periodic geometry, and report cutoff sensitivity, exchange-aware residence, direct coincidence, networks, and observed representatives.", ("accepted solvated trajectories", "explicit solute and water connectivity", "standard water residue identity", "interaction scope", "primary and sensitivity geometry rules", "resource gates"), ("sparse frame water paths", "observed bridge dictionary", "cutoff-resolved bridge occupancies", "any-water and same-water residence runs", "network summaries", "representative frame locators"), ("The first implementation supports exactly one bridging water, not multi-water wires or proton hopping.", "The observed bridge union is not an outcome-independent machine-learning feature universe.", "Water-network geometry and occupancy do not establish energy, affinity, causality, or mechanism."), status="experimental"),
    _module("grouped_ml", "Grouped-validation machine learning", "md", "11", "Run deterministic decision-tree classification with complete segment-time-block holdouts, confusion matrices, and held-out permutation diagnostics; estimator extensions remain explicit.", ("KMeans PCA feature table", "explicit KMeans technical target", "segment/time-block group labels", "tree and permutation settings"), ("fold and pooled held-out metrics", "confusion matrices", "final tree", "impurity and held-out permutation diagnostics"), ("Chance-level performance and impurity importance alone do not support mechanism.", "The current target is a technical clustering target derived from the input features and is not a biological endpoint.", "Random-forest support remains a separately validated extension."), status="experimental"),
    _module("grouped_regularized_classification", "Grouped logistic and elastic-net classification", "md", "11M", "Classify declared systems from hydrogen-bond patterns using nested leave-one-group-out selection of L2 logistic and elastic-net models, outer held-out metrics, coefficients, and training-only top-feature ablations.", ("hydrogen-bond discovery matrix", "system targets", "replica, segment, or time-block groups", "regularization grids"), ("nested tuning diagnostics", "outer held-out metrics", "coefficients", "top-feature and no-top-feature ablations"), ("Replica grouping is preferred; time blocks cannot manufacture independent replicas.", "Predictive coefficients and performance are not causal or mechanistic evidence.", "Every class requires at least two independent groups."), status="experimental"),
    _module("secondary_structure", "Secondary structure", "md", "12", "Execute an explicitly selected mkdssp binary on local temporary per-frame PDBs and retain executable/version, frame, residue, and periodicity provenance.", ("accepted trajectories", "PDB topology", "mkdssp executable", "frame and resource gates"), ("frame assignment counts", "residue-level DSSP code populations", "executable provenance", "periodicity diagnostics"), ("Pooled estimates must retain replica-sensitive uncertainty.", "The external mkdssp executable is required and no heuristic method is mislabeled as DSSP.", "The executable's code alphabet is preserved: DSSP 4.6 PPII code P must be mapped explicitly before comparison with older code alphabets.", "Periodic production analysis requires explicit connectivity-aware reconstruction."), status="experimental"),
    _module("nucleic_acid_structure", "Nucleic-acid structural motifs", "md", "12N", "Execute an explicitly selected x3dna-dssr binary in JSON mode on temporary per-frame PDBs and retain executable/version, requested collection fields, explicit wildcard numeric descriptors, frame identities, and replica-resolved summaries.", ("accepted trajectories", "PDB/GRO topology", "x3dna-dssr executable", "declared JSON collection fields and optional numeric-query paths", "frame, timeout, and resource gates"), ("frame-level motif collection counts", "numeric base-pair/base-step/groove/helical/backbone/sugar descriptors requested by path", "replica summaries", "observed JSON keys", "executable and command provenance"), ("DSSR is an external dependency; JSON paths and missing-value policies must be declared explicitly and may vary by DSSR version.", "Periodic production analysis requires connectivity-aware reconstruction.", "Motif counts and structural descriptors require replica-sensitive convergence analysis."), status="experimental"),
    _module("nucleic_acid_geometry", "Intrinsic nucleic-acid ring and stacking geometry", "md", "12G", "Calculate explicit-ring fitted-plane displacement, cyclic torsion departure from 0/180 degrees, signed centering, declared fused-ring fold and base-stacking plane angles, centroid distances, early/late drift, blocks, and independent Scott/FD/Rice distributions.", ("accepted trajectories", "PDB/GRO topology", "cyclic ordered ring atom indices", "declared fused-ring or stacking pairs", "stride, block, histogram, and resource gates"), ("frame-level intrinsic ring metrics", "fused-fold and stacking geometry", "replica and block summaries", "early/late shifts", "histograms, assignments, and segment-safe residence runs"), ("Intrinsic ring puckering, whole-base reorientation, fused-ring fold, and stacking are distinct metrics.", "Ring identities and pass thresholds belong in project or publication locks.", "Periodic production analysis requires connectivity-aware reconstruction."), status="experimental"),
    _module("ion_coordination_geometry", "Bound-ion coordination and ion-pair geometry", "md", "12I", "Analyze arbitrary declared bound ions, candidate coordinating atoms, ion-pair distances, coordination numbers, ligand identities and occupancies, nearest distances, and rotation-free pair-angle deviations from declared ideal coordination templates.", ("accepted trajectories", "PDB/GRO topology", "explicit ion and candidate-ligand atom indices", "coordination cutoffs", "optional ion pairs and geometry templates", "histogram and resource gates"), ("frame-level coordination records", "bound-ligand identities and occupancies", "ion-pair distances", "geometry-template scores", "replica/block summaries and independent scalar distributions"), ("Coordination cutoffs and ideal templates are project-specific and must be sensitivity-tested.", "Geometric agreement does not determine electronic structure, protonation, affinity, or catalytic importance.", "Pass thresholds and biological interpretation belong in project or publication locks."), status="experimental"),
    _module("ion_atmosphere", "Species-resolved ion atmosphere", "md", "12A", "Measure exact triclinic minimum-image shells for every supported ion species actually present around all-solute, protein, nucleic-acid, and ligand/cofactor polar target groups, retaining system, replica, segment, frame, species, charge-class, and ion identity.", ("accepted periodic trajectories", "PDB/GRO topology", "species-resolved ion atom indices", "polar target atom groups", "shell cutoffs and frame gates"), ("species-target shell timeseries", "species-resolved shell summaries", "per-ion inner-shell occupancy and descriptive persistence", "frame and periodicity provenance"), ("Atmosphere shells and persistence classes are geometric and do not establish biological binding, affinity, oxidation state, or mechanism.", "Shell cutoffs require chemistry-specific sensitivity analysis.", "Cross-replica, oligomer-member, and cross-system inference requires an explicit independent-unit model."), status="experimental"),
    _module("solvent_accessible_surface_area", "Solvent-accessible surface area", "md", "12", "Calculate deterministic atom-, residue-, and selection-level Shrake-Rupley SASA using explicit surface and occluder selections, Bondi-style radii, probe radius, sphere-point resolution, and periodic reconstruction policy.", ("accepted trajectories", "PDB/GRO topology", "named surface and occluder selections", "probe and resolution settings"), ("atom and residue SASA", "selection total timeseries", "replica summaries", "periodicity and algorithm provenance"), ("Project execution refuses fewer than 240 sphere points and warns below the 960-point cross-validation setting; publication comparisons still require resolution sensitivity.", "Wrapped periodic execution is refused; connectivity-aware reconstruction is required.", "Disconnected-component image conventions require independent validation.", "Surface-area changes do not establish binding, stability, or mechanism."), status="experimental"),
    _module("radial_distribution_functions", "Radial distribution functions", "md", "12R", "Calculate replica-resolved radial distribution functions for explicit atom groups using triclinic minimum-image distances, exact spherical-shell volumes, per-frame cell-volume normalization, and safe half-cell radius gates.", ("accepted trajectories with periodic cells", "PDB/GRO topology", "explicit atom-index groups", "radial range, bin width, stride, and resource gates"), ("raw and uniform-expected shell counts", "g(r) by replica", "cell-volume and pair-count provenance", "segment evaluation counts"), ("The radial range may not exceed half the minimum triclinic face height.", "Replica RDFs remain separate until an independent-unit pooling model is declared.", "RDF peaks do not by themselves establish specific interactions, binding, or mechanism."), status="experimental"),
    _module("optional_observables", "Question-driven optional observables", "md", "12", "Evaluate extensible question-linked observables; the current base slice implements explicit pair and group-distance families, contacts, and reference-defined native-contact fractions, while domain-specific ring, ion, and RDF analyses retain separate contracts.", ("accepted trajectories", "observable question", "explicit atom-index specification", "distance/contact/native-reference threshold where applicable"), ("observable timeseries", "distance summaries", "contact and native-contact occupancies", "periodicity and provenance diagnostics"), ("Modules must answer a declared scientific or structural question.", "Water networks, membrane deformation, and experimental forward models require separately validated extensions.", "Raw wrapped-coordinate distances are diagnostic only."), status="experimental"),
    _module("convergence_uncertainty", "Convergence, uncertainty, and population validity", "md", "13", "Evaluate declared RMSD/Rg block stability, split-mean agreement, overlap-normalized autocorrelation sequences, initial-positive-sequence effective sample size, autocorrelation-adjusted mean uncertainty, and population-validity gates; optional replica summaries are exploratory only.", ("replica RMSD/Rg or other scalar timeseries", "replica and segment labels", "block, autocorrelation, ESS, and split-mean gates", "optional replica-diagnostics choice"), ("per-series convergence and autocorrelation diagnostics", "effective-sample-size-adjusted uncertainty", "optional exploratory between-replica summaries", "population-validity status", "failed-gate evidence"), ("Incompatible sampling methods cannot be pooled without an explicit calibration model.", "Autocorrelation, ESS, and block analyses are diagnostics rather than proof of independent sampling.", "Replica agreement and leave-one-replica-out are not acceptance measures.", "Population validity requires all declared non-replica gates, not merely technical execution."), status="experimental"),
    _module("integrated_comparison", "Integrated comparative analysis", "reporting", "14", "Extract prespecified RFC-6901 values from validated module reports while preserving raw values, failures, source statuses, and interpretation types without hidden aggregation.", ("project manifest", "supported module outputs", "entry IDs and value pointers", "interpretation types", "failure policy"), ("integrated raw-value table", "source-module status table", "upstream issues", "explicit no-aggregation contract"), ("Exploratory prioritization must remain separate from inferential claims.", "The current base integrator does not calculate composite scores.", "A shared table does not change the evidentiary status of its rows."), status="experimental"),
    _module("alternative_clustering", "Alternative clustering and validation", "md", "8A", "Run distinctly labeled PAM, Minkowski-weighted PAM, Ward, Gaussian and variational mixtures, affinity propagation, mean shift, and quality-threshold clustering while scanning declared parameters; predictive or medoid families can fit deterministic replica-balanced samples and assign selected partitions to every source observation, while Ward and quality-threshold are skipped unless an exact complete fit is affordable and fully assigned.", ("tICA, common PCA, or declared trajectory features", "algorithm-specific parameter grids", "one planner-selected fit budget or optional sensitivity budgets", "silhouette and algorithm resource gates"), ("all parameter-sweep or explicit skip records", "sampled-fit identities and coverage", "all-frame selected assignments and populations where supported", "exact or model-based extension identity", "medoids/centers/weights", "silhouette, Calinski-Harabasz, Davies-Bouldin, and cross-budget adjusted-Rand diagnostics"), ("Different algorithms are not treated as interchangeable.", "Ward and quality-threshold never receive approximate all-frame extensions.", "An all-frame assignment from another sampled fitted model is not equivalent to refitting the algorithm on all frames.", "Geometric separation and budget agreement do not establish metastability, convergence, or kinetics.", "PaLD community structure is a separate module and is not ranked as a conventional partition."), status="experimental"),
    _module("pald_community_analysis", "Partitioned Local Depth community analysis", "md", "8P", "Calculate PaLD cohesion, local depth, mutual-cohesion networks, the universal strong-tie threshold, connected strong-tie communities, core and boundary observations, and an optional separately labeled sampled-community MSM on one regular replica-member-balanced sample.", ("tICA, common PCA, or declared trajectory features", "strict cubic observation gate", "replica, member, segment, frame, and physical-time identities", "optional Markov-model settings"), ("cohesion and mutual-cohesion matrices", "local-depth values", "strong-tie threshold and graph", "community labels and cores", "intercommunity ties", "optional sampled PaLD-community MSM"), ("PaLD is a community-network analysis rather than a conventional all-frame clustering method.", "Equivalent oligomer members are separate observations but not independent replicas.", "The cubic calculation requires bounded regular sampling.", "Cohesion and communities do not establish kinetics, pathways, metastability, causality, or convergence.", "Any community MSM is reported separately and never competes for best-clustering selection."), status="experimental"),
    _module("information_dynamics", "Directional and higher-order information dynamics", "md", "5D", "Calculate segment-safe finite-bin transfer entropy, source-at-t to target-at-t-plus-lag cross-correlation, third-order coskewness, and displacement-propagator observables with explicit lag and resource gates.", ("declared feature segments or vector displacements", "lag/bin settings", "resource gates"), ("source-to-target transfer-entropy matrix", "directional lagged cross-correlation matrix", "coskewness tensor", "normalized propagator"), ("Finite-bin estimates require sensitivity analysis.", "Directional dependence does not establish causal mechanism.", "Lag pairs never cross segments."), status="experimental"),
    _module("correlation_networks", "Correlation networks and profile clustering", "md", "5R", "Convert signed DCCM or reference-difference matrices into thresholded networks with edges, degree, strength, components, and local clustering coefficients; optionally cluster correlation profiles with the reference HDBSCAN package using declared signed-profile or absolute-similarity distances.", ("complete DCCM matrices", "absolute threshold", "negative-edge policy", "optional HDBSCAN profile-clustering settings"), ("signed edge table", "node metrics", "connected components", "optional canonical profile-cluster labels and noise assignments"), ("Network topology and profile clustering are threshold- and parameter-sensitive.", "Correlation edges and clusters are not direct physical interactions or causal links.", "The optional HDBSCAN dependency must be installed separately."), status="experimental"),
    _module("trajectory_features", "Reusable trajectory feature extractors", "md", "6F", "Extract declared Cartesian, fluctuation, center-of-mass, center-of-geometry, pair-distance, group min/mean/max distance, minimum-mean group distance, COM/COG distance, and mass-weighted principal-axis features with frame identities and periodic reconstruction.", ("accepted trajectories", "topologies", "atom-index feature definitions"), ("segment-resolved feature records", "distance statistics and selected atom-pair identities", "centers", "principal moments and relative axes"), ("Feature and group-aggregation definitions must be frozen before comparison.", "Project-specific physical meanings belong in manifests, not package source."), status="experimental"),
    _module("scalar_feature_distributions", "Scalar feature histograms and residence runs", "md", "6H", "Build explicit, Scott, Freedman-Diaconis, or Rice histograms for declared scalar trajectory features and calculate segment-safe, boundary-censored residence runs without joining discontinuous trajectories.", ("trajectory feature records", "feature/value identity", "binning rule and gates", "observation gate"), ("raw histogram counts and frame assignments", "automatic-rule width evidence", "segment-safe residence runs", "complete and censored run summaries"), ("Histogram and residence estimates require bin and stride sensitivity.", "Residence runs never cross declared segment boundaries.", "Histogram occupancy and residence do not establish convergence, metastability, kinetics, or mechanism."), status="experimental"),
    _module("scalar_threshold_states", "Scalar threshold states", "md", "6T", "Convert declared scalar trajectory features into explicit two-state definitions with threshold sensitivity, system/replica populations, segment-safe transitions, and boundary-censored residence runs.", ("trajectory feature records", "feature/value identity", "primary and sensitivity thresholds", "state labels"), ("frame state assignments", "system/replica population comparisons", "threshold sensitivity", "segment-safe transitions and residence"), ("Thresholds must be frozen before comparative outcome review.", "Frame counts require correlation-aware uncertainty and physical-time conversion.", "A distance threshold is an operational binding definition, not affinity or binding free energy."), status="experimental"),
    _module("hydrogen_bond_patterns", "Hydrogen-bond pattern clustering", "md", "11P", "Encode explicit frame-level bond IDs as binary patterns and cluster them using Jaccard PAM or the optional reference HDBSCAN implementation.", ("explicit hydrogen-bond observations", "bond-ID dictionary", "clustering settings"), ("binary pattern matrix", "Jaccard distances", "cluster labels and medoids/noise"), ("Patterns inherit the upstream hydrogen-bond definition.", "Clusters are descriptive and do not establish energetic or mechanistic importance."), status="experimental"),
    _module("representative_structures", "Average and observed representative structures", "md", "8S", "Calculate arithmetic mean coordinates, the observed frame closest to the mean, the medoid, and central observed frames for a prealigned ensemble.", ("aligned common-atom coordinates", "optional frame weights"), ("labeled arithmetic mean", "closest observed frame", "medoid", "central-frame set"), ("Arithmetic means need not be chemically valid structures.", "Inputs must already share a validated atom order and alignment basis."), status="experimental"),
    _module("rmsf_permutation_inference", "RMSF permutation inference", "md", "13R", "Compare independent replica- or time-block RMSF profiles with exact or seeded Monte Carlo label permutations and max-T familywise adjustment.", ("group-resolved RMSF profiles", "exchangeability declaration", "permutation settings"), ("mean-difference profile", "pointwise p-values", "max-T adjusted p-values"), ("Rows, not frames, are the exchangeable units.", "Exchangeability and multiplicity choices require scientific justification."), status="experimental"),
)


_BY_ID = {module.module_id: module for module in MODULES}
if len(_BY_ID) != len(MODULES):
    raise RuntimeError("Duplicate module IDs in registry")


def list_modules() -> List[ModuleSpec]:
    return list(MODULES)


def get_module(module_id: str) -> ModuleSpec:
    try:
        return _BY_ID[module_id]
    except KeyError as exc:
        raise KeyError(f"Unknown analysis module: {module_id}") from exc
